### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by jhsiao999**
* Update homepage
* Local copy of `poisthin.R`
* add `sctransform` package to `environment.yaml`

### CODE REVIEW

**Comment by jhsiao999** [comment]
@jdblischak Just bringing your attention to my updates in the conda environment. I added `sctransform`. We would need this for the methods. Thanks.

**Comment by jdblischak** [comment]
@jhsiao999 To install sctransform for the CI builds, please add `r-sctransform` to the file `requirements/conda-forge`. I tried doing it myself, but I don't have push access to ~~your fork~~ the main repository.

**Comment by jdblischak** [comment]
Though I don't think that is why the builds failed.

Here is the error message from CircleCI:

https://circleci.com/gh/stephenslab/dsc-log-fold-change/41

```
DEBUG: parse_simple -> <Simple name: $auc_est, value: auc_est>
  File "/opt/conda/lib/python3.6/site-packages/dsc/__main__.py", line 343, in main
    args.func(args)
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/dsc/__main__.py", line 343, in main
    args.func(args)
  File "/opt/conda/lib/python3.6/site-packages/dsc/__main__.py", line 62, in execute
    script = DSC_Script(args.dsc_file, output = args.output, sequence = args.target, truncate = args.truncate, replicate = 1 if args.truncate else args.replicate)
  File "/opt/conda/lib/python3.6/site-packages/dsc/dsc_parser.py", line 101, in __init__
    if try_get_value(self.content, ('DSC', 'define')) else ''))
dsc.utils.FormatError: Module or group name ``data`` is not defined!
Available modules are ``data_poisthin_choose_betasd, deseq2, edger, glm_pois, glm_quasipois, limma_voom, sva_limma_voom, t_test_log2p1, t_test_log2p1_cpm_quant, wilcoxon, qvalue, type1error, fdr, auc, data_poisthin, data_poisthin_gtex, data_poisthin_libsize``
Available groups are ``make_data, run_methods, rank_pvals, score_methods``
ERROR: Module or group name data is not defined!
Available modules are data_poisthin_choose_betasd, deseq2, edger, glm_pois, glm_quasipois, limma_voom, sva_limma_voom, t_test_log2p1, t_test_log2p1_cpm_quant, wilcoxon, qvalue, type1error, fdr, auc, data_poisthin, data_poisthin_gtex, data_poisthin_libsize
Available groups are make_data, run_methods, rank_pvals, score_methods
Exited with code 1
```

And here is the error message from Travis:

https://travis-ci.org/stephenslab/dsc-log-fold-change/builds/529518972#L2313

```
INFO: Running data_poisthin_gtex: 
INFO: Running wilcoxon: 
ERROR: [998b26c7-986e-4a77-8cf6-867c531e04d3]: [data_poisthin_gtex]: 
Failed to execute Rscript .sos/data_poisthin_gtex_0_08a3ce73.R
exitcode=1, workdir=/home/travis/build/stephenslab/dsc-log-fold-change/dsc, stderr=benchmark/data_poisthin_gtex/data_poisthin_gtex_1.stderr
---------------------------------------------------------------------------
[DSC]: 35 pending steps: DSC, t_qvalue, s_qvalue, r_qvalue, q_qvalue, p_qvalue, o_qvalue, n_qvalue, m_qvalue, l_qvalue, k_qvalue, j_qvalue, i_qvalue, h_qvalue, g_qvalue, f_qvalue, e_qvalue, d_qvalue, c_qvalue, b_qvalue, a_qvalue, n_wilcoxon, m_t_test_log2p1_cpm_quant, l_t_test_log2p1, k_limma_voom, j_deseq2, i_edger, h_wilcoxon, g_t_test_log2p1_cpm_quant, f_t_test_log2p1, e_limma_voom, d_deseq2, c_edger, b_limma_voom, a_edger
WARNING: Files in green in the error prompt above contains codes and error info to help debug.
Scripts upstream of the error can be found in benchmark.scripts.html.
INFO: Elapsed time 16.794 seconds.
The command "dsc benchmark.dsc --truncate -c 1 -v 3" exited with 1.
```

**Comment by jhsiao999** [comment]
@jdblischak I added `r-sctransform` to `requirements/conda-forge`. 

The CircleCI built error looks like it could be related to the dsc script syntax. I've been making some changes lately, partly to simplify the script and partly to extend the benchmarks. Perhaps we should wait till I have tested out my changes before digging into the CircleCI built error?  What do you think?

**Comment by jdblischak** [comment]
> The CircleCI built error looks like it could be related to the dsc script syntax. I've been making some changes lately, partly to simplify the script and partly to extend the benchmarks. Perhaps we should wait till I have tested out my changes before digging into the CircleCI built error? What do you think?

@jhsiao999 Agreed. I confirmed that r-sctransform was installed.

**Review by jdblischak — APPROVED** [review]

**Pull request merged**
