### PR TITLE
Update DSC version and command-line options

### PR DESCRIPTION
**Pull request by jdblischak**

### CODE REVIEW

**Comment by jdblischak** [comment]
@jhsiao999 Could you please also confirm that the setting "Build forked pull requests" is set to On? This setting should be available at https://circleci.com/gh/stephenslab/dsc-log-fold-change/edit#advanced-settings

**Comment by jhsiao999** [comment]
@jdblischak I just changed it to ON! Maybe this addresses most of the failed tests?

**Comment by jdblischak** [comment]
Thanks! But no, the builds are failing because for whatever reason the bioconda channel metadata can't be downloaded at the moment.

**Comment by jdblischak** [comment]
@jhsiao999 Builds passed! Also note that I just uploaded seqgendiff 0.2.0 to Anaconda Cloud, so it should be used in the builds that get triggered post-merge.

https://anaconda.org/jdblischak/r-seqgendiff/files?version=0.2.0

**Pull request merged**
